import type {
  BoardSummary,
  BoardDetail,
  BoardCardModel,
  BoardMember,
  BoardColumn,
} from "./types";

const currentUserEmail = "you@grove.local";

const sharedMembers: BoardMember[] = [
  { email: currentUserEmail, name: "You", avatarColor: "#f59e0b", role: "manager" },
  { email: "lin@grove.local", name: "Lin", avatarColor: "#3b82f6", role: "operator" },
  { email: "river@grove.local", name: "River", avatarColor: "#10b981", role: "operator" },
  { email: "kai@grove.local", name: "Kai", avatarColor: "#a855f7", role: "viewer" },
];

const baseColumns = (): BoardColumn[] => [
  { id: "col-backlog", name: "Backlog", anchor: "backlog" },
  { id: "col-progress", name: "In Progress" },
  { id: "col-review", name: "Review" },
  { id: "col-done", name: "Done", anchor: "done" },
];

const minimalColumns = (): BoardColumn[] => [
  { id: "col-backlog", name: "Backlog", anchor: "backlog" },
  { id: "col-doing", name: "Doing" },
  { id: "col-done", name: "Done", anchor: "done" },
];

export const MOCK_BOARDS: BoardSummary[] = [
  {
    id: "board-1",
    name: "Q2 Platform Roadmap",
    mode: "online",
    branch: "grove/board/q2-platform",
    primaryProjectName: "grove",
    linkedProjectCount: 3,
    memberCount: 4,
    cardCount: 12,
    sessionCount: 7,
    sync: "synced",
    lastActiveAt: "2026-05-11T08:14:00Z",
  },
  {
    id: "board-2",
    name: "Personal Cleanup",
    mode: "offline",
    primaryProjectName: "grove",
    linkedProjectCount: 1,
    memberCount: 1,
    cardCount: 5,
    sessionCount: 2,
    sync: "offline",
    lastActiveAt: "2026-05-09T22:30:00Z",
  },
  {
    id: "board-3",
    name: "Studio: Brand Refresh",
    mode: "online",
    branch: "grove/board/brand-refresh",
    primaryProjectName: "studio-brand",
    linkedProjectCount: 2,
    memberCount: 3,
    cardCount: 8,
    sessionCount: 1,
    sync: "syncing",
    lastActiveAt: "2026-05-11T10:02:00Z",
  },
];

export const MOCK_BOARD_DETAILS: Record<string, BoardDetail> = {
  "board-1": {
    ...MOCK_BOARDS[0],
    columns: baseColumns(),
    members: sharedMembers,
    projects: [
      { id: "proj-grove", name: "grove", primary: true },
      { id: "proj-grove-web", name: "grove-web", primary: false },
      { id: "proj-grove-mcp", name: "grove-mcp", primary: false },
    ],
    currentUserEmail,
  },
  "board-2": {
    ...MOCK_BOARDS[1],
    columns: minimalColumns(),
    members: [sharedMembers[0]],
    projects: [{ id: "proj-grove", name: "grove", primary: true }],
    currentUserEmail,
  },
  "board-3": {
    ...MOCK_BOARDS[2],
    columns: baseColumns(),
    members: sharedMembers.slice(0, 3),
    projects: [
      { id: "proj-studio-brand", name: "studio-brand", primary: true },
      { id: "proj-design-system", name: "design-system", primary: false },
    ],
    currentUserEmail,
  },
};

export const MOCK_CARDS: Record<string, BoardCardModel[]> = {
  "board-1": [
    {
      id: "card-1",
      boardId: "board-1",
      columnId: "col-progress",
      title: "Migrate task storage to SQLite",
      description:
        "Move legacy per-task JSON into the unified SQLite schema. Includes migration tooling.",
      assigneeEmail: "lin@grove.local",
      startAt: "2026-05-08",
      dueAt: "2026-05-14",
      ownerEmail: "lin@grove.local",
      sessions: [
        {
          id: "s-1",
          taskId: "t-101",
          taskName: "migrate-storage",
          taskKind: "worktree",
          status: "working",
          ownerEmail: "lin@grove.local",
          agentId: "claude",
          preview: "Refactor migration runner to stream rows in batches.",
          elapsedSeconds: 142,
          todoCompleted: 3,
          todoTotal: 8,
        },
        {
          id: "s-2",
          taskId: "t-101",
          taskName: "migrate-storage",
          taskKind: "worktree",
          status: "idle",
          ownerEmail: "lin@grove.local",
          agentId: "codex",
          preview: "Investigate the legacy notes folder layout.",
          elapsedSeconds: 1080,
        },
      ],
      createdAt: "2026-05-04T09:00:00Z",
      updatedAt: "2026-05-11T08:14:00Z",
    },
    {
      id: "card-2",
      boardId: "board-1",
      columnId: "col-progress",
      title: "ACP session fork support",
      description:
        "Allow forking from an existing session checkpoint to explore alternative branches.",
      assigneeEmail: currentUserEmail,
      startAt: "2026-05-10",
      dueAt: "2026-05-18",
      ownerEmail: currentUserEmail,
      sessions: [
        {
          id: "s-3",
          taskId: "t-102",
          taskName: "acp-fork",
          taskKind: "worktree",
          status: "working",
          ownerEmail: currentUserEmail,
          agentId: "claude",
          preview: "Add forkFrom() to the session manager and route through ACP.",
          elapsedSeconds: 38,
          todoCompleted: 1,
          todoTotal: 5,
        },
      ],
      createdAt: "2026-05-09T12:00:00Z",
      updatedAt: "2026-05-11T07:55:00Z",
    },
    {
      id: "card-3",
      boardId: "board-1",
      columnId: "col-backlog",
      title: "Board sync conflict UI",
      description:
        "Design and implement merge conflict resolution UI for the board sync layer.",
      ownerEmail: null,
      sessions: [],
      createdAt: "2026-05-07T15:00:00Z",
      updatedAt: "2026-05-07T15:00:00Z",
    },
    {
      id: "card-4",
      boardId: "board-1",
      columnId: "col-backlog",
      title: "Cross-project session aggregation",
      assigneeEmail: "river@grove.local",
      startAt: "2026-05-15",
      ownerEmail: null,
      sessions: [],
      createdAt: "2026-05-06T10:30:00Z",
      updatedAt: "2026-05-06T10:30:00Z",
    },
    {
      id: "card-5",
      boardId: "board-1",
      columnId: "col-review",
      title: "Tray popover navigation regression",
      description: "Fix the tray popover losing nav state on rapid open/close cycles.",
      assigneeEmail: "river@grove.local",
      startAt: "2026-05-05",
      dueAt: "2026-05-11",
      ownerEmail: "river@grove.local",
      sessions: [
        {
          id: "s-4",
          taskId: "t-103",
          taskName: "tray-nav-fix",
          taskKind: "worktree",
          status: "done",
          ownerEmail: "river@grove.local",
          agentId: "claude",
          preview: "Add regression test for double-fire onNavigate.",
          durationSeconds: 3720,
        },
      ],
      createdAt: "2026-05-04T16:00:00Z",
      updatedAt: "2026-05-11T05:00:00Z",
    },
    {
      id: "card-6",
      boardId: "board-1",
      columnId: "col-done",
      title: "Mobile drawer LAN auth",
      assigneeEmail: "kai@grove.local",
      startAt: "2026-04-28",
      dueAt: "2026-05-05",
      ownerEmail: "kai@grove.local",
      sessions: [
        {
          id: "s-5",
          taskId: "t-104",
          taskName: "mobile-auth",
          taskKind: "worktree",
          status: "done",
          ownerEmail: "kai@grove.local",
          agentId: "gemini",
          preview: "Sign requests with HMAC + nonce; reject replays.",
          durationSeconds: 10800,
        },
      ],
      createdAt: "2026-04-26T11:00:00Z",
      updatedAt: "2026-05-05T19:00:00Z",
    },
  ],
  "board-2": [
    {
      id: "card-21",
      boardId: "board-2",
      columnId: "col-doing",
      title: "Clean up stale worktrees",
      assigneeEmail: currentUserEmail,
      startAt: "2026-05-09",
      ownerEmail: currentUserEmail,
      sessions: [
        {
          id: "s-21",
          taskId: "_local",
          taskName: "_local",
          taskKind: "local",
          status: "idle",
          ownerEmail: currentUserEmail,
          agentId: "claude",
          preview: "List worktrees older than 30d and propose removal.",
          elapsedSeconds: 7200,
        },
      ],
      createdAt: "2026-05-09T08:00:00Z",
      updatedAt: "2026-05-09T22:00:00Z",
    },
    {
      id: "card-22",
      boardId: "board-2",
      columnId: "col-backlog",
      title: "Document local-task shortcuts",
      ownerEmail: null,
      sessions: [],
      createdAt: "2026-05-08T09:00:00Z",
      updatedAt: "2026-05-08T09:00:00Z",
    },
    {
      id: "card-23",
      boardId: "board-2",
      columnId: "col-done",
      title: "Backup old notes folder",
      assigneeEmail: currentUserEmail,
      startAt: "2026-05-01",
      dueAt: "2026-05-03",
      ownerEmail: currentUserEmail,
      sessions: [],
      createdAt: "2026-04-30T10:00:00Z",
      updatedAt: "2026-05-03T11:00:00Z",
    },
  ],
  "board-3": [
    {
      id: "card-31",
      boardId: "board-3",
      columnId: "col-progress",
      title: "Color palette exploration",
      assigneeEmail: "lin@grove.local",
      ownerEmail: "lin@grove.local",
      startAt: "2026-05-10",
      dueAt: "2026-05-17",
      sessions: [
        {
          id: "s-31",
          taskId: "t-301",
          taskName: "brand-palette",
          taskKind: "worktree",
          status: "working",
          ownerEmail: "lin@grove.local",
          agentId: "claude",
          preview: "Generate 6 palette directions with rationale.",
          elapsedSeconds: 305,
        },
      ],
      createdAt: "2026-05-10T13:00:00Z",
      updatedAt: "2026-05-11T09:50:00Z",
    },
    {
      id: "card-32",
      boardId: "board-3",
      columnId: "col-backlog",
      title: "Logo lockup variants",
      ownerEmail: null,
      sessions: [],
      createdAt: "2026-05-08T14:00:00Z",
      updatedAt: "2026-05-08T14:00:00Z",
    },
  ],
};

export const CURRENT_USER_EMAIL = currentUserEmail;
