/**
 * Demo data for diff review UI development.
 * Access via /review/demo/demo
 */
import type { FullDiffResult } from '../../api/review';
import type { ReviewCommentEntry } from '../../api/tasks';

export interface VersionOption {
  id: string;
  label: string;
  ref?: string;  // git ref (commit hash); undefined for 'latest' and 'target'
}

export const DEMO_VERSIONS: VersionOption[] = [
  { id: 'latest',  label: 'Latest' },
  { id: 'v3',      label: 'Version 3' },
  { id: 'v2',      label: 'Version 2' },
  { id: 'v1',      label: 'Version 1' },
  { id: 'target',  label: 'Base' },
];

export const DEMO_DIFF: FullDiffResult = {
  total_additions: 87,
  total_deletions: 34,
  files: [
    // 1. Modified file — typical code change with multiple hunks
    {
      old_path: 'src/app.rs',
      new_path: 'src/app.rs',
      change_type: 'modified',
      is_binary: false,
      additions: 15,
      deletions: 8,
      hunks: [
        {
          old_start: 1,
          old_lines: 7,
          new_start: 1,
          new_lines: 8,
          header: '@@ -1,7 +1,8 @@ use std::collections::HashMap;',
          lines: [
            { line_type: 'context', old_line: 1, new_line: 1, content: 'use std::collections::HashMap;' },
            { line_type: 'context', old_line: 2, new_line: 2, content: 'use std::path::PathBuf;' },
            { line_type: 'delete', old_line: 3, new_line: null, content: 'use std::sync::Mutex;' },
            { line_type: 'insert', old_line: null, new_line: 3, content: 'use std::sync::{Arc, Mutex};' },
            { line_type: 'insert', old_line: null, new_line: 4, content: 'use tokio::sync::RwLock;' },
            { line_type: 'context', old_line: 4, new_line: 5, content: '' },
            { line_type: 'context', old_line: 5, new_line: 6, content: 'pub struct AppState {' },
            { line_type: 'context', old_line: 6, new_line: 7, content: '    config: Config,' },
            { line_type: 'context', old_line: 7, new_line: 8, content: '    tasks: Vec<Task>,' },
          ],
        },
        {
          old_start: 42,
          old_lines: 12,
          new_start: 43,
          new_lines: 18,
          header: '@@ -42,12 +43,18 @@ impl AppState {',
          lines: [
            { line_type: 'context', old_line: 42, new_line: 43, content: '    pub fn new() -> Self {' },
            { line_type: 'context', old_line: 43, new_line: 44, content: '        let config = Config::load().unwrap_or_default();' },
            { line_type: 'delete', old_line: 44, new_line: null, content: '        let tasks = Vec::new();' },
            { line_type: 'delete', old_line: 45, new_line: null, content: '        Self { config, tasks }' },
            { line_type: 'insert', old_line: null, new_line: 45, content: '        let tasks = storage::load_tasks(&config.project_key)' },
            { line_type: 'insert', old_line: null, new_line: 46, content: '            .unwrap_or_default();' },
            { line_type: 'insert', old_line: null, new_line: 47, content: '        let watcher = FileWatcher::new(&config.project_path);' },
            { line_type: 'insert', old_line: null, new_line: 48, content: '' },
            { line_type: 'insert', old_line: null, new_line: 49, content: '        Self {' },
            { line_type: 'insert', old_line: null, new_line: 50, content: '            config,' },
            { line_type: 'insert', old_line: null, new_line: 51, content: '            tasks,' },
            { line_type: 'insert', old_line: null, new_line: 52, content: '            watcher: Some(watcher),' },
            { line_type: 'insert', old_line: null, new_line: 53, content: '        }' },
            { line_type: 'context', old_line: 46, new_line: 54, content: '    }' },
            { line_type: 'context', old_line: 47, new_line: 55, content: '' },
            { line_type: 'delete', old_line: 48, new_line: null, content: '    pub fn refresh(&mut self) {' },
            { line_type: 'delete', old_line: 49, new_line: null, content: '        self.tasks = Vec::new();' },
            { line_type: 'insert', old_line: null, new_line: 56, content: '    pub fn refresh(&mut self) -> Result<()> {' },
            { line_type: 'insert', old_line: null, new_line: 57, content: '        self.tasks = storage::load_tasks(&self.config.project_key)?;' },
            { line_type: 'insert', old_line: null, new_line: 58, content: '        Ok(())' },
            { line_type: 'context', old_line: 50, new_line: 59, content: '    }' },
            { line_type: 'context', old_line: 51, new_line: 60, content: '}' },
          ],
        },
      ],
    },

    // 2. New file (added)
    {
      old_path: '/dev/null',
      new_path: 'src/diff/mod.rs',
      change_type: 'added',
      is_binary: false,
      additions: 32,
      deletions: 0,
      hunks: [
        {
          old_start: 0,
          old_lines: 0,
          new_start: 1,
          new_lines: 32,
          header: '@@ -0,0 +1,32 @@',
          lines: [
            { line_type: 'insert', old_line: null, new_line: 1, content: '//! Diff parser module' },
            { line_type: 'insert', old_line: null, new_line: 2, content: '' },
            { line_type: 'insert', old_line: null, new_line: 3, content: 'use serde::Serialize;' },
            { line_type: 'insert', old_line: null, new_line: 4, content: '' },
            { line_type: 'insert', old_line: null, new_line: 5, content: '#[derive(Debug, Clone, Serialize)]' },
            { line_type: 'insert', old_line: null, new_line: 6, content: 'pub struct DiffLine {' },
            { line_type: 'insert', old_line: null, new_line: 7, content: '    pub line_type: String,' },
            { line_type: 'insert', old_line: null, new_line: 8, content: '    pub old_line: Option<u32>,' },
            { line_type: 'insert', old_line: null, new_line: 9, content: '    pub new_line: Option<u32>,' },
            { line_type: 'insert', old_line: null, new_line: 10, content: '    pub content: String,' },
            { line_type: 'insert', old_line: null, new_line: 11, content: '}' },
            { line_type: 'insert', old_line: null, new_line: 12, content: '' },
            { line_type: 'insert', old_line: null, new_line: 13, content: '#[derive(Debug, Clone, Serialize)]' },
            { line_type: 'insert', old_line: null, new_line: 14, content: 'pub struct DiffHunk {' },
            { line_type: 'insert', old_line: null, new_line: 15, content: '    pub old_start: u32,' },
            { line_type: 'insert', old_line: null, new_line: 16, content: '    pub old_lines: u32,' },
            { line_type: 'insert', old_line: null, new_line: 17, content: '    pub new_start: u32,' },
            { line_type: 'insert', old_line: null, new_line: 18, content: '    pub new_lines: u32,' },
            { line_type: 'insert', old_line: null, new_line: 19, content: '    pub header: String,' },
            { line_type: 'insert', old_line: null, new_line: 20, content: '    pub lines: Vec<DiffLine>,' },
            { line_type: 'insert', old_line: null, new_line: 21, content: '}' },
            { line_type: 'insert', old_line: null, new_line: 22, content: '' },
            { line_type: 'insert', old_line: null, new_line: 23, content: 'pub fn parse_diff(raw: &str) -> DiffResult {' },
            { line_type: 'insert', old_line: null, new_line: 24, content: '    let mut files = Vec::new();' },
            { line_type: 'insert', old_line: null, new_line: 25, content: '    // ... parsing logic' },
            { line_type: 'insert', old_line: null, new_line: 26, content: '    DiffResult {' },
            { line_type: 'insert', old_line: null, new_line: 27, content: '        files,' },
            { line_type: 'insert', old_line: null, new_line: 28, content: '        total_additions: 0,' },
            { line_type: 'insert', old_line: null, new_line: 29, content: '        total_deletions: 0,' },
            { line_type: 'insert', old_line: null, new_line: 30, content: '    }' },
            { line_type: 'insert', old_line: null, new_line: 31, content: '}' },
            { line_type: 'insert', old_line: null, new_line: 32, content: '' },
          ],
        },
      ],
    },

    // 3. Deleted file
    {
      old_path: 'src/difit.rs',
      new_path: '/dev/null',
      change_type: 'deleted',
      is_binary: false,
      additions: 0,
      deletions: 18,
      hunks: [
        {
          old_start: 1,
          old_lines: 18,
          new_start: 0,
          new_lines: 0,
          header: '@@ -1,18 +0,0 @@',
          lines: [
            { line_type: 'delete', old_line: 1, new_line: null, content: '//! External difit integration' },
            { line_type: 'delete', old_line: 2, new_line: null, content: '' },
            { line_type: 'delete', old_line: 3, new_line: null, content: 'use std::process::Command;' },
            { line_type: 'delete', old_line: 4, new_line: null, content: '' },
            { line_type: 'delete', old_line: 5, new_line: null, content: 'pub enum DifitAvailability {' },
            { line_type: 'delete', old_line: 6, new_line: null, content: '    Global,' },
            { line_type: 'delete', old_line: 7, new_line: null, content: '    Npx,' },
            { line_type: 'delete', old_line: 8, new_line: null, content: '    NotAvailable,' },
            { line_type: 'delete', old_line: 9, new_line: null, content: '}' },
            { line_type: 'delete', old_line: 10, new_line: null, content: '' },
            { line_type: 'delete', old_line: 11, new_line: null, content: 'pub fn check_available() -> DifitAvailability {' },
            { line_type: 'delete', old_line: 12, new_line: null, content: '    if Command::new("difit").arg("--version")' },
            { line_type: 'delete', old_line: 13, new_line: null, content: '        .output().is_ok() {' },
            { line_type: 'delete', old_line: 14, new_line: null, content: '        DifitAvailability::Global' },
            { line_type: 'delete', old_line: 15, new_line: null, content: '    } else {' },
            { line_type: 'delete', old_line: 16, new_line: null, content: '        DifitAvailability::NotAvailable' },
            { line_type: 'delete', old_line: 17, new_line: null, content: '    }' },
            { line_type: 'delete', old_line: 18, new_line: null, content: '}' },
          ],
        },
      ],
    },

    // 4. Renamed file (with small changes)
    {
      old_path: 'src/review_state.rs',
      new_path: 'src/review/state.rs',
      change_type: 'renamed',
      is_binary: false,
      additions: 5,
      deletions: 3,
      hunks: [
        {
          old_start: 1,
          old_lines: 8,
          new_start: 1,
          new_lines: 10,
          header: '@@ -1,8 +1,10 @@',
          lines: [
            { line_type: 'delete', old_line: 1, new_line: null, content: '//! Review state management' },
            { line_type: 'insert', old_line: null, new_line: 1, content: '//! Review state management (refactored)' },
            { line_type: 'context', old_line: 2, new_line: 2, content: '' },
            { line_type: 'delete', old_line: 3, new_line: null, content: 'use std::collections::HashMap;' },
            { line_type: 'insert', old_line: null, new_line: 3, content: 'use std::collections::BTreeMap;' },
            { line_type: 'insert', old_line: null, new_line: 4, content: 'use serde::{Serialize, Deserialize};' },
            { line_type: 'context', old_line: 4, new_line: 5, content: '' },
            { line_type: 'delete', old_line: 5, new_line: null, content: 'pub struct ReviewState {' },
            { line_type: 'insert', old_line: null, new_line: 6, content: '#[derive(Debug, Clone, Serialize, Deserialize)]' },
            { line_type: 'insert', old_line: null, new_line: 7, content: 'pub struct ReviewState {' },
            { line_type: 'context', old_line: 6, new_line: 8, content: '    pub comments: Vec<Comment>,' },
            { line_type: 'context', old_line: 7, new_line: 9, content: '    pub status: ReviewStatus,' },
            { line_type: 'context', old_line: 8, new_line: 10, content: '}' },
          ],
        },
      ],
    },

    // 5. Binary file
    {
      old_path: 'assets/logo.png',
      new_path: 'assets/logo.png',
      change_type: 'modified',
      is_binary: true,
      additions: 0,
      deletions: 0,
      hunks: [],
    },

    // 6. Config/TOML (small change)
    {
      old_path: 'Cargo.toml',
      new_path: 'Cargo.toml',
      change_type: 'modified',
      is_binary: false,
      additions: 3,
      deletions: 1,
      hunks: [
        {
          old_start: 1,
          old_lines: 7,
          new_start: 1,
          new_lines: 9,
          header: '@@ -1,7 +1,9 @@ [package]',
          lines: [
            { line_type: 'context', old_line: 1, new_line: 1, content: '[package]' },
            { line_type: 'context', old_line: 2, new_line: 2, content: 'name = "grove-rs"' },
            { line_type: 'delete', old_line: 3, new_line: null, content: 'version = "0.4.5"' },
            { line_type: 'insert', old_line: null, new_line: 3, content: 'version = "0.4.6"' },
            { line_type: 'context', old_line: 4, new_line: 4, content: 'edition = "2021"' },
            { line_type: 'context', old_line: 5, new_line: 5, content: '' },
            { line_type: 'context', old_line: 6, new_line: 6, content: '[dependencies]' },
            { line_type: 'insert', old_line: null, new_line: 7, content: 'serde_json = "1.0"' },
            { line_type: 'insert', old_line: null, new_line: 8, content: 'open = "5"' },
            { line_type: 'context', old_line: 7, new_line: 9, content: 'ratatui = "0.29"' },
          ],
        },
      ],
    },

    // 7. TypeScript/TSX file (frontend change)
    {
      old_path: 'grove-web/src/components/Review/DiffFileView.tsx',
      new_path: 'grove-web/src/components/Review/DiffFileView.tsx',
      change_type: 'modified',
      is_binary: false,
      additions: 12,
      deletions: 4,
      hunks: [
        {
          old_start: 10,
          old_lines: 10,
          new_start: 10,
          new_lines: 18,
          header: '@@ -10,10 +10,18 @@ interface Props {',
          lines: [
            { line_type: 'context', old_line: 10, new_line: 10, content: 'interface Props {' },
            { line_type: 'context', old_line: 11, new_line: 11, content: '  file: DiffFile;' },
            { line_type: 'delete', old_line: 12, new_line: null, content: '  viewType: string;' },
            { line_type: 'insert', old_line: null, new_line: 12, content: "  viewType: 'unified' | 'split';" },
            { line_type: 'context', old_line: 13, new_line: 13, content: '  isActive: boolean;' },
            { line_type: 'insert', old_line: null, new_line: 14, content: '  comments?: ReviewCommentEntry[];' },
            { line_type: 'insert', old_line: null, new_line: 15, content: '  commentFormLine?: string | null;' },
            { line_type: 'insert', old_line: null, new_line: 16, content: '  onGutterClick?: (location: string) => void;' },
            { line_type: 'insert', old_line: null, new_line: 17, content: '  onAddComment?: (location: string, content: string) => void;' },
            { line_type: 'insert', old_line: null, new_line: 18, content: '  onDeleteComment?: (id: number) => void;' },
            { line_type: 'insert', old_line: null, new_line: 19, content: '  onCancelComment?: () => void;' },
            { line_type: 'context', old_line: 14, new_line: 20, content: '}' },
            { line_type: 'context', old_line: 15, new_line: 21, content: '' },
            { line_type: 'delete', old_line: 16, new_line: null, content: 'export function DiffFileView({ file, viewType, isActive }: Props) {' },
            { line_type: 'delete', old_line: 17, new_line: null, content: '  const ref = useRef<HTMLDivElement>(null);' },
            { line_type: 'insert', old_line: null, new_line: 22, content: 'export function DiffFileView({' },
            { line_type: 'insert', old_line: null, new_line: 23, content: '  file, viewType, isActive,' },
            { line_type: 'insert', old_line: null, new_line: 24, content: '  comments = [], commentFormLine,' },
            { line_type: 'insert', old_line: null, new_line: 25, content: '  onGutterClick, onAddComment, onDeleteComment, onCancelComment,' },
            { line_type: 'delete', old_line: 18, new_line: null, content: '' },
            { line_type: 'insert', old_line: null, new_line: 26, content: '}: Props) {' },
            { line_type: 'insert', old_line: null, new_line: 27, content: '  const ref = useRef<HTMLDivElement>(null);' },
          ],
        },
      ],
    },

    // 8. Long file with many lines (to test scrolling)
    {
      old_path: 'src/storage/comments.rs',
      new_path: 'src/storage/comments.rs',
      change_type: 'modified',
      is_binary: false,
      additions: 20,
      deletions: 0,
      hunks: [
        {
          old_start: 100,
          old_lines: 5,
          new_start: 100,
          new_lines: 25,
          header: '@@ -100,5 +100,25 @@ pub fn load_comments() -> Result<Vec<Comment>> {',
          lines: [
            { line_type: 'context', old_line: 100, new_line: 100, content: '    Ok(comments)' },
            { line_type: 'context', old_line: 101, new_line: 101, content: '}' },
            { line_type: 'context', old_line: 102, new_line: 102, content: '' },
            { line_type: 'insert', old_line: null, new_line: 103, content: '/// Add a new comment to the comments.json store' },
            { line_type: 'insert', old_line: null, new_line: 104, content: 'pub fn add_comment(' },
            { line_type: 'insert', old_line: null, new_line: 105, content: '    project: &str,' },
            { line_type: 'insert', old_line: null, new_line: 106, content: '    task_id: &str,' },
            { line_type: 'insert', old_line: null, new_line: 107, content: '    location: &str,' },
            { line_type: 'insert', old_line: null, new_line: 108, content: '    content: &str,' },
            { line_type: 'insert', old_line: null, new_line: 109, content: ') -> Result<Comment> {' },
            { line_type: 'insert', old_line: null, new_line: 110, content: '    let mut data = load_comments_json(project, task_id)?' },
            { line_type: 'insert', old_line: null, new_line: 111, content: '        .unwrap_or_default();' },
            { line_type: 'insert', old_line: null, new_line: 112, content: '    let id = data.comments.iter()' },
            { line_type: 'insert', old_line: null, new_line: 113, content: '        .map(|c| c.id).max().unwrap_or(0) + 1;' },
            { line_type: 'insert', old_line: null, new_line: 114, content: '    let comment = Comment {' },
            { line_type: 'insert', old_line: null, new_line: 115, content: '        id,' },
            { line_type: 'insert', old_line: null, new_line: 116, content: '        location: location.to_string(),' },
            { line_type: 'insert', old_line: null, new_line: 117, content: '        content: content.to_string(),' },
            { line_type: 'insert', old_line: null, new_line: 118, content: '        status: "open".to_string(),' },
            { line_type: 'insert', old_line: null, new_line: 119, content: '        reply: None,' },
            { line_type: 'insert', old_line: null, new_line: 120, content: '    };' },
            { line_type: 'insert', old_line: null, new_line: 121, content: '    data.comments.push(comment.clone());' },
            { line_type: 'insert', old_line: null, new_line: 122, content: '    save_comments_json(project, task_id, &data)?;' },
            { line_type: 'context', old_line: 103, new_line: 123, content: '    Ok(comment)' },
            { line_type: 'context', old_line: 104, new_line: 124, content: '}' },
          ],
        },
      ],
    },
  ],
};

export const DEMO_COMMENTS: ReviewCommentEntry[] = [
  {
    id: 1,
    file_path: 'src/app.rs',
    side: 'ADD' as const,
    start_line: 45,
    end_line: 45,
    content: 'This initialization logic should handle errors more gracefully. Consider using `unwrap_or_default()` with a warning log instead of silently falling back.',
    author: 'You',
    timestamp: '2 hours ago',
    status: 'open',
    replies: [],
  },
  {
    id: 2,
    file_path: 'src/app.rs',
    side: 'ADD' as const,
    start_line: 56,
    end_line: 56,
    content: 'The `refresh()` method now returns `Result<()>` — make sure all call sites handle the error.',
    author: 'Claude Code',
    timestamp: '1 hour ago',
    status: 'resolved',
    replies: [
      { id: 1, content: 'Fixed: updated all 3 call sites to use `?` operator.', author: 'You', timestamp: '30 min ago' },
    ],
  },
  {
    id: 3,
    file_path: 'src/storage/comments.rs',
    side: 'ADD' as const,
    start_line: 110,
    end_line: 113,
    content: 'Potential race condition: two concurrent calls could assign the same ID. Consider using a UUID or atomic counter.',
    author: 'Cursor',
    timestamp: '3 hours ago',
    status: 'open',
    replies: [],
  },
  {
    id: 4,
    file_path: 'Cargo.toml',
    side: 'ADD' as const,
    start_line: 3,
    end_line: 3,
    content: 'Version bump looks good — but have we updated the CHANGELOG for 0.4.6?',
    author: 'Gemini',
    timestamp: '4 hours ago',
    status: 'open',
    replies: [],
  },
  {
    id: 5,
    file_path: 'src/diff/mod.rs',
    side: 'ADD' as const,
    start_line: 23,
    end_line: 23,
    content: 'The `parse_diff` function currently returns hardcoded zeroes for totals. This needs to accumulate from parsed files.',
    author: 'GitHub Copilot',
    timestamp: '5 hours ago',
    status: 'outdated',
    replies: [
      { id: 1, content: 'Acknowledged — will fix once the full parser is wired up.', author: 'Claude Code', timestamp: '4 hours ago' },
    ],
  },
];
